# Generated by Django 4.0.5 on 2022-09-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_background_options_background_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinglePics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='profile/')),
                ('get_image_str', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
