# Generated by Django 4.0.5 on 2022-09-08 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_singlepics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SinglePics',
        ),
    ]
