# Generated by Django 4.0.5 on 2022-09-08 10:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_singlepics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('date_added',), 'verbose_name_plural': 'profile_pics'},
        ),
        migrations.AddField(
            model_name='profile',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
