# Generated by Django 4.0.5 on 2022-09-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_profile_options_profile_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='background',
            options={'verbose_name_plural': 'background_pics'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'profile_pics'},
        ),
        migrations.AddField(
            model_name='background',
            name='get_image_str',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='background',
            name='image',
            field=models.ImageField(upload_to='profile/'),
        ),
    ]
