# Generated by Django 4.0.5 on 2022-09-08 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_background_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='background',
            options={'ordering': ('date_added',), 'verbose_name_plural': 'background_pics'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('date_added',), 'verbose_name_plural': 'profile_pics'},
        ),
    ]
