# Generated by Django 4.0.5 on 2022-09-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_background_options_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='image',
            field=models.ImageField(upload_to='background/'),
        ),
    ]
