# Generated by Django 4.1.1 on 2022-09-08 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_selectedproduct_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='background',
            options={'ordering': ('-date_added',), 'verbose_name_plural': 'background_pics'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('-date_added',), 'verbose_name_plural': 'profile_pics'},
        ),
    ]
